[package]
name = "erso"
version = "0.1.0"
edition = "2024"

[dependencies]
pmrpc = { path = "../../pmrpc" }
tokio = { version = "1.48.0", features = ["full"] }
turso = "0.3.2"
wincode = { version = "0.2.5", features = ["derive"] }
